service: kube-credential-ecr

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}

custom:
  accountId: ${aws:accountId}
  region: ${self:provider.region}
  stage: ${self:provider.stage}

resources:
  Resources:
    # ECR Repositories
    IssuanceECRRepository:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: issuance-service
        ImageScanningConfiguration:
          ScanOnPush: true
        LifecyclePolicy:
          LifecyclePolicyText: |
            {
              "rules": [
                {
                  "rulePriority": 1,
                  "selection": {
                    "tagStatus": "untagged",
                    "countType": "sinceImagePushed",
                    "countUnit": "days",
                    "countNumber": 7
                  },
                  "action": {
                    "type": "expire"
                  }
                }
              ]
            }

    VerificationECRRepository:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: verification-service
        ImageScanningConfiguration:
          ScanOnPush: true
        LifecyclePolicy:
          LifecyclePolicyText: |
            {
              "rules": [
                {
                  "rulePriority": 1,
                  "selection": {
                    "tagStatus": "untagged",
                    "countType": "sinceImagePushed",
                    "countUnit": "days",
                    "countNumber": 7
                  },
                  "action": {
                    "type": "expire"
                  }
                }
              ]
            }

  Outputs:
    IssuanceECRRepository:
      Description: Issuance Service ECR Repository URI
      Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/issuance-service"
      Export:
        Name: ${self:service}-${self:provider.stage}-issuance-ecr

    VerificationECRRepository:
      Description: Verification Service ECR Repository URI
      Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/verification-service"
      Export:
        Name: ${self:service}-${self:provider.stage}-verification-ecr